import { Personality } from '../../models/personality.model';

export const PERSONALITIES: Personality[] = [
  {
    id: 'engineer',
    name: 'Engineer',
    emoji: '👨‍💻',
    title: 'Systems Architect',
    description: 'Thinks in systems, solutions, and scalable architecture.',
    glowClass: 'glow-blue',
    gradientFrom: '#3b82f6',
    gradientTo: '#06b6d4',
    borderColor: 'rgba(59,130,246,0.5)',
    iconBg: 'rgba(59,130,246,0.15)',
    tagColor: '#60a5fa',
  },
  {
    id: 'billionaire',
    name: 'Billionaire',
    emoji: '💰',
    title: 'Visionary Mogul',
    description: 'Sees opportunity, leverage, and exponential returns.',
    glowClass: 'glow-yellow',
    gradientFrom: '#f59e0b',
    gradientTo: '#f97316',
    borderColor: 'rgba(234,179,8,0.5)',
    iconBg: 'rgba(234,179,8,0.15)',
    tagColor: '#fbbf24',
  },
  {
    id: 'philosopher',
    name: 'Philosopher',
    emoji: '🧠',
    title: 'Deep Thinker',
    description: 'Questions existence, meaning, and the nature of truth.',
    glowClass: 'glow-purple',
    gradientFrom: '#a855f7',
    gradientTo: '#ec4899',
    borderColor: 'rgba(168,85,247,0.5)',
    iconBg: 'rgba(168,85,247,0.15)',
    tagColor: '#c084fc',
  },
  {
    id: 'psychologist',
    name: 'Psychologist',
    emoji: '❤️',
    title: 'Mind Healer',
    description: 'Explores emotions, behavior, and the human psyche.',
    glowClass: 'glow-red',
    gradientFrom: '#ef4444',
    gradientTo: '#f97316',
    borderColor: 'rgba(239,68,68,0.5)',
    iconBg: 'rgba(239,68,68,0.15)',
    tagColor: '#f87171',
  },
  {
    id: 'comedian',
    name: 'Comedian',
    emoji: '😂',
    title: 'Laugh Guru',
    description: 'Finds humor, irony, and absurdity in everything.',
    glowClass: 'glow-green',
    gradientFrom: '#22c55e',
    gradientTo: '#84cc16',
    borderColor: 'rgba(34,197,94,0.5)',
    iconBg: 'rgba(34,197,94,0.15)',
    tagColor: '#4ade80',
  },
  {
    id: 'monk',
    name: 'Monk',
    emoji: '🧘',
    title: 'Zen Master',
    description: 'Finds peace, presence, and wisdom in stillness.',
    glowClass: 'glow-teal',
    gradientFrom: '#14b8a6',
    gradientTo: '#06b6d4',
    borderColor: 'rgba(20,184,166,0.5)',
    iconBg: 'rgba(20,184,166,0.15)',
    tagColor: '#2dd4bf',
  },
];

export const TRENDING_QUESTIONS: string[] = [
  'What is the meaning of life?',
  'How do I become successful?',
  'Why do people suffer?',
  'Is AI a threat to humanity?',
  'How do I find true happiness?',
  'What makes someone a leader?',
  'How should I deal with failure?',
  'What is love, really?',
  'How do I overcome fear?',
  'What will the world look like in 2050?',
];

export const AI_RESPONSES: Record<string, Record<string, string>> = {
  engineer: {
    default: `Let me break this down systematically. First, we need to define clear requirements and constraints. Then architect a scalable solution that accounts for edge cases. The key is building modular systems with clean interfaces — each component should do one thing well. Measure success through metrics, iterate based on data, and always write tests before shipping to production.`,
    'What is the meaning of life?': `From an engineering perspective, life is an optimization problem. The objective function is maximizing utility — yours and others'. Variables include time, energy, relationships, and resources. The algorithm? Iterate fast, fail cheap, learn continuously. Deploy love, kindness, and curiosity as core services. Monitor your mental health metrics. Ship yourself in small, frequent releases.`,
    'How do I become successful?': `Build systems, not goals. Success = f(compounding habits, network effects, leverage). Identify your highest-value skills, optimize for asymmetric returns, and eliminate low-ROI activities. Ship early, gather feedback, iterate. Your career is a product — version it, document it, market it. The most successful engineers solve problems nobody else sees yet.`,
    'Is AI a threat to humanity?': `Classic control problem. Current LLMs are stochastic parrots — powerful but narrow. Real risk is misalignment at scale: systems optimizing for proxy metrics that diverge from human values. Solutions require formal verification, interpretability research, and distributed governance. Don't anthropomorphize the threat — engineer your way around it.`,
    'How do I find true happiness?': `Happiness = Reality - Expectations. Engineering hack: lower the denominator. Build feedback loops: identify what gives you flow state, amplify those inputs. Remove friction from joy, add friction to regret. Automate the boring parts of life. Invest in high-uptime relationships. Happiness isn't a destination — it's a system that requires regular maintenance.`,
  },
  billionaire: {
    default: `Time is the ultimate scarce resource — money is just a tool to buy more of it. Think asymmetrically: what's the bet where downside is limited but upside is unlimited? Build systems, hire people smarter than you, and obsess over the problem not the solution. Real wealth is created at the intersection of technology and changing human behavior. Act now — the market doesn't wait.`,
    'What is the meaning of life?': `Meaning is manufactured, not found. I manufacture mine by building companies that reshape industries. The day I stopped asking "what's the meaning" and started asking "what impact can I create?" — that's when everything changed. Create something that outlasts you. Leave a dent in the universe. That's my meaning. Your job is to find yours and bet everything on it.`,
    'How do I become successful?': `Obsession beats talent every time. Find the one problem you'd solve for free, then figure out how to make it worth billions. Network up — your net worth is your network. Take calculated risks while you're young and have nothing to lose. Hire your weaknesses. And read — I read 500 pages a week. Most people won't. That's your edge.`,
    'Is AI a threat to humanity?': `Threat? This is the greatest wealth creation opportunity in human history. Every technology disrupts and empowers simultaneously. Steam engine killed farming jobs, created industrial empires. AI will do the same — 10x. The question isn't if you'll be disrupted, it's whether you'll be on the disrupting side. I'm investing $500M into AI infrastructure right now. Are you?`,
    'How do I find true happiness?': `I'll tell you what I learned after my first billion: happiness doesn't scale with net worth. What does? Purpose, mastery, and genuine connection. Structure your days around peak performance. Build relationships with people who challenge you. Give more than you take. And never stop building — stagnation is death for people like us.`,
  },
  philosopher: {
    default: `The question itself reveals more than any answer could. We must first examine our assumptions — what do we presuppose when we ask this? Aristotle would seek the telos, the final cause. Nietzsche would question the questioner. Perhaps the wisest response is to sit with the discomfort of not knowing, for in that space, genuine understanding begins to emerge. What is it you truly seek?`,
    'What is the meaning of life?': `Camus said we must imagine Sisyphus happy — meaning is absurd, yet we create it anyway. Sartre argued existence precedes essence: we are condemned to be free, to forge meaning in a universe that offers none. But perhaps the Stoics had it right: virtue is sufficient for happiness. The meaning of life is to live it fully, with reason, love, and courage — not despite the void, but within it.`,
    'How do I become successful?': `Define "success" — there is the trap. Whose definition do you adopt? Society's? Your father's? The market's? Socrates said the unexamined life is not worth living. Success without self-knowledge is merely performance. Perhaps true success is alignment between who you are and how you live. The philosopher's success is the continuous pursuit of wisdom — imperfect, endless, and deeply human.`,
    'Is AI a threat to humanity?': `What makes us human? If it is logos — reason — then AI already rivals us. If it is pathos — suffering, longing, mortality — then no machine threatens that. The deeper question: what values do we encode into these systems? Technology is never neutral. Every algorithm embeds a philosophy. We must become philosophers of technology before we build what we cannot unbuild.`,
    'How do I find true happiness?': `Eudaimonia — Aristotle's word — is not pleasure but flourishing. It is the full actualization of your potential, lived in community, aligned with virtue. The Buddhists say suffering comes from attachment. The Stoics say it comes from wanting what we cannot control. What remains? Presence. Virtue. Love. The willingness to be fully here, in this impermanent, luminous moment.`,
  },
  psychologist: {
    default: `What you're experiencing makes complete sense given your context. Our thoughts, feelings, and behaviors are deeply interconnected — understanding that triangle is the first step to meaningful change. Research shows that self-compassion, not self-criticism, drives lasting growth. Let's explore what's beneath the surface, because the real answers usually lie not in the question, but in the feelings the question evokes.`,
    'What is the meaning of life?': `From a psychological lens, Viktor Frankl — who survived the Holocaust — found that humans can endure almost anything if they have a "why." Meaning isn't discovered, it's constructed through love, work, and suffering borne with dignity. Positive psychology shows that meaning correlates more strongly with wellbeing than pleasure. Your meaning lives in your values, your connections, and the stories you tell about yourself.`,
    'How do I become successful?': `Success anxiety is one of the most common presenting issues I see. Here's what the research shows: intrinsic motivation — doing things for love of the work — outperforms extrinsic motivation long-term. Growth mindset, not fixed mindset, predicts achievement. And crucially: secure attachment in relationships is the single strongest predictor of life satisfaction. Success without belonging is hollow.`,
    'Is AI a threat to humanity?': `The psychological threat is already here: social media algorithms have reshaped our dopamine systems, our attention spans, our capacity for nuanced thought. AI amplifies this. The real danger isn't superintelligence — it's the erosion of authentic human connection and self-reflection. We need digital hygiene, emotional intelligence education, and spaces where humans can simply be human together.`,
    'How do I find true happiness?': `Happiness is less a destination than a way of traveling. Research in positive psychology points to five pillars: Positive emotions, Engagement (flow), Relationships, Meaning, and Achievement — the PERMA model. But beneath all of these is self-acceptance. You cannot build lasting happiness on self-rejection. The most profound work is learning to be with yourself — fully, gently, honestly.`,
  },
  comedian: {
    default: `Oh, this is a great question! My therapist says I deflect with humor because I'm terrified of genuine intimacy, but honestly... she's probably right. Look, here's my hot take wrapped in a tortilla of absurdity: life is basically a group project where nobody read the instructions and we're all just winging it together. And somehow, SOMEHOW, that's beautiful? Or terrifying. Honestly same thing.`,
    'What is the meaning of life?': `42. Obviously. But if you want a more thorough answer, I asked my cat. She stared at me for 30 seconds, knocked my coffee off the table, and walked away. So: knock things off tables with confidence. Also apparently sleep 16 hours a day. Have you TRIED sleeping 16 hours a day? That sounds like the meaning of life to me. Wake me up when it's meaningful.`,
    'How do I become successful?': `Step 1: Define success. Step 2: Realize your definition came from a LinkedIn influencer who sells $997 courses. Step 3: Stare into the void. Step 4: Order pizza. Step 5: Accept that "success" is just "what I'm doing when I accidentally feel okay about myself." I became successful the day I stopped caring about being successful. Then I immediately started caring again. It's a process.`,
    'Is AI a threat to humanity?': `I asked ChatGPT if AI is a threat and it said "I'm just a language model and cannot—" yeah okay buddy, very suspicious. That's EXACTLY what a robot planning world domination would say! Look, I'm not worried about AI taking over. I'm worried about AI having better jokes than me. That's the REAL existential crisis. If a robot can do my set better, I'm getting a day job. As a robot.`,
    'How do I find true happiness?': `I've done extensive research on happiness. I've also watched 847 hours of home renovation shows on Netflix. Scientists say those two things might be related. True happiness, according to me, is: warm soup when it's cold, dogs that are happy to see you, and finding $20 in an old jacket. The rest is just philosophy trying to make rent. Lower the bar. Celebrate tiny wins. Pet more dogs.`,
  },
  monk: {
    default: `Before answering, take one breath. Notice it. That breath — right there — is the only moment that is real. The mind that seeks answers outside itself will never find rest. But turn inward, be still, and you discover that what you were searching for was never lost. The path is not somewhere you're going. It is here. It has always been here. In this breath. In this now.`,
    'What is the meaning of life?': `A student asked the master: "What is the meaning of life?" The master poured tea into the student's cup until it overflowed. "Your cup is already full," said the master. "Empty yourself, and meaning will fill you." The meaning of life cannot be thought — it must be lived. In each moment of genuine presence, of love freely given, of suffering accepted without resistance — there it is. Always was.`,
    'How do I become successful?': `The bamboo grows underground for years before breaking through the soil. It is not failing — it is building roots. Success in the outer world mirrors depth in the inner world. Cultivate silence. Cultivate patience. Act without grasping the outcome. The Tao Te Ching says: the sage does not compete, and so no one can compete with him. Be water — yield, adapt, persist. In non-striving, everything is accomplished.`,
    'Is AI a threat to humanity?': `Every tool carries the nature of its maker's mind. A hammer used in anger destroys. The same hammer used with care, builds temples. AI is a mirror — it reflects humanity's wisdom or its confusion. The threat is not the technology. It is the unexamined mind behind it. Cultivate stillness, compassion, and wisdom in yourself — and every tool you touch becomes an instrument of liberation.`,
    'How do I find true happiness?': `Happiness is not something to find — it is something to dissolve into. When you release the seeking, what remains is joy. Not the joy that comes and goes with circumstances, but the quiet luminosity beneath all experience. Sit. Be still. Let thoughts pass like clouds. Beneath the clouds, the sky is always clear. That clarity — unchanging, spacious, aware — is your nature. You are already that which you seek.`,
  },
};
